### ISSUE TITLE
mapping works incorrectly in 3001

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#72] opened 2016-11-02 19:01 UTC
Compare http://suave.sdsc.edu:3000/snapshot/581a374adca3054378447433 and http://suave.sdsc.edu:3001/snapshot/581a37680f6c3a17fbb7e2e7 

in 3001, it doesn't show date and number variables correctly

**Comment by izaslavsky** [comment] 2016-11-09 21:39
The fix broke another map:
http://suave.sdsc.edu:3001/main/file=zaslavsk_SDG_Indicators.csv&views=111010&view=grid
switch to map, select "SDGI rank" to map - it won't work.

I guess we need to test everything again before I can send out the newsletter.
Could you fix and test?

**Comment by liside** [comment] 2016-11-10 07:23
fixed the additional problem. Testing now

**Comment by izaslavsky** [comment] 2016-11-10 10:56
http://suave.sdsc.edu:3001/main/file=zaslavsk_SDG_Indicators.csv&views=111010&view=grid
now SDGI_Score doesn't work, though SDGI_Rank works

**Comment by liside** [comment] 2016-11-10 15:17
The above problem was caused by floating point. Fixed now.

**Comment by liside** [comment] 2016-11-10 15:17
let me test it more with #number tags

**Closed as completed** 2016-11-15 00:06 UTC
Labels: bug
